# Generated by Django 5.0.6 on 2024-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_type_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('vintage_book', 'Vintage Book'), ('children_teenagers', 'Children and Teenager'), ('manga_comics', 'Manga and Comic'), ('ebook_audiobook', 'Ebook and Audiobook')], max_length=50),
        ),
    ]
