# Generated by Django 5.0.6 on 2024-12-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_added_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
