# Generated by Django 5.0.6 on 2024-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_customer_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('book', 'Libri'), ('children_teenagers', 'Bambini e Ragazzi'), ('manga_comics', 'Manga'), ('vintage_book', 'Libri Vintage'), ('ebook_audiobook', 'eBook e Audiolibri')], max_length=50),
        ),
    ]
