# Generated by Django 5.0.6 on 2024-12-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_reviewrating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
    ]
