# Generated by Django 4.2 on 2024-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_supplier',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review_supplier',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review_supplier',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
