# Generated by Django 4.2 on 2024-12-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_supplier',
            name='rating',
            field=models.FloatField(),
        ),
    ]
