# Generated by Django 4.2 on 2024-12-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
