# Generated by Django 4.2 on 2024-12-11 09:06
from django.utils import timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_delete_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
