# Generated by Django 5.0.6 on 2024-12-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_shipping_email_order_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_p',
            old_name='name',
            new_name='name_surname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_name',
            new_name='shipping_name_surname',
        ),
    ]
