# Generated by Django 5.0.6 on 2024-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_orderitem_buyer_alter_orderitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
