# Generated by Django 5.0.6 on 2024-12-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_p_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='date_shipped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
