# Generated by Django 5.0.6 on 2024-12-04 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_remove_orderitem_buyer_remove_orderitem_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_p',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order_p',
            name='supplier',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
