# Generated by Django 5.0.6 on 2024-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_remove_order_p_shipped_orderitem_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='shipped_order',
            field=models.BooleanField(default=False),
        ),
    ]
