# Generated by Django 5.0.6 on 2024-12-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_order_p_shipped_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_p',
            name='shipped_order',
        ),
    ]
