# Generated by Django 5.0.6 on 2024-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
