# Generated by Django 5.0.6 on 2024-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_order_p_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_p',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
