# Generated by Django 5.0.6 on 2024-12-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_order_p_paid_order_p_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_p',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order_p',
            name='read',
        ),
        migrations.RemoveField(
            model_name='order_p',
            name='received',
        ),
    ]
