# Generated by Django 5.0.6 on 2024-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
