# Generated by Django 5.0.6 on 2024-12-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_orderitem_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='received',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
