# Generated by Django 5.0.6 on 2024-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_remove_orderitem_received_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
    ]
