# Generated by Django 5.0.6 on 2024-12-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
