# Generated by Django 5.0.6 on 2024-12-06 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='message_read',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipped',
        ),
    ]
