# Generated by Django 5.0.6 on 2024-12-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_remove_orderitem_message_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
