# Generated by Django 5.0.6 on 2024-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_orderitem_message_read_orderitem_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
