# Generated by Django 5.0.6 on 2024-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_orderitem_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
