# Generated by Django 4.2 on 2024-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_alter_orderitem_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_p',
            name='data_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
